[toolchain]
anchor_version = "0.29.0"
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
slipless_hook = "8YpmSCdxjdznYuQtSUpeerjb53iDq4uWW34T9gLF2t2p"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.devnet.solana.com"
wallet = "/home/skipp/Documents/projects/slipless/slipless_main_wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
